"""Enterprise automation testing platform - shared framework core.

This package provides the shared testing capabilities (configuration, logging,
context, capability clients, test infrastructure, reporting, and plugin hooks)
consumed by all business-system test suites under ``projects/``.

Phase 1 adds the configuration center, exception hierarchy, HTTP client,
database client, Redis cache client, and message-queue client to the core.
The context module provides trace_id correlation across the request lifecycle.
"""

from framework.core import (
    DEFAULT_TRACE_HEADER,
    AppEnv,
    CacheError,
    ClientConnectionError,
    ClientError,
    ClientStatusError,
    ClientTimeoutError,
    ConfigError,
    ContextError,
    DatabaseError,
    DatabaseSettings,
    DatabaseType,
    DependencyError,
    FrameworkError,
    FrameworkSettings,
    HttpExchange,
    HttpSettings,
    KafkaSettings,
    MQError,
    MQSettings,
    MQType,
    RedisSettings,
    RegistryError,
    RequestRecorder,
    TestContext,
    YamlEnvSettingsSource,
    bind_context,
    bind_recorder,
    clear_context,
    clear_recorder,
    current_trace_id,
    format_record_as_json,
    get_context,
    get_logger,
    get_recorder,
    get_settings,
    log_exception,
    log_request,
    new_trace_id,
    record_exchange,
    reset_settings,
    set_context,
    setup_logging,
    trace,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_TRACE_HEADER",
    "AppEnv",
    "CacheError",
    "ClientConnectionError",
    "ClientError",
    "ClientStatusError",
    "ClientTimeoutError",
    "ConfigError",
    "ContextError",
    "DatabaseError",
    "DatabaseSettings",
    "DatabaseType",
    "DependencyError",
    "FrameworkError",
    "FrameworkSettings",
    "HttpExchange",
    "HttpSettings",
    "KafkaSettings",
    "MQError",
    "MQSettings",
    "MQType",
    "RedisSettings",
    "RegistryError",
    "RequestRecorder",
    "TestContext",
    "YamlEnvSettingsSource",
    "__version__",
    "bind_context",
    "bind_recorder",
    "clear_context",
    "clear_recorder",
    "current_trace_id",
    "format_record_as_json",
    "get_context",
    "get_logger",
    "get_recorder",
    "get_settings",
    "log_exception",
    "log_request",
    "new_trace_id",
    "record_exchange",
    "reset_settings",
    "set_context",
    "setup_logging",
    "trace",
]
